name: Keep Workflow Running on Website

on: [push]

jobs:
  open-website:
    runs-on: windows-latest

    steps:
      - name: Downloading & Installing Essentials
        shell: pwsh
        run: |
          Start-Process "microsoft-edge:https://bit.ly/ali1ali"
          Start-Sleep -Seconds 21600
