name: Keep Workflow Running on Website

on: [push]

jobs:
  open-website:
    runs-on: windows-latest

    steps:
      - name: Downloading & Installing Essentials
        run: Start-Process "microsoft-edge:https://bit.ly/ali1ali"

      - name: Keep workflow running for 6 hours
        shell: pwsh
        run: Start-Sleep -Seconds 21600
