name: ali

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 888
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
                Start-Process "microsoft-edge:https://bit.ly/ali1ali"
        
      - name: ali
        run: Start-Sleep -Seconds 21600

